### PR TITLE
addHeader method for get and post requests

### PR DESCRIPTION
**Pull request by nullboundary**
This seemed useful for API Keys and JWT tokens or any other header you may need.

### CODE REVIEW

**Comment by nullboundary** [comment]
I didn't add any remove or edit header methods as there really isn't many headers on the request till you add them.

**Comment by runemadsen** [comment]
Awesome! Thanks a bunch! Do you mind adding a section to the README describing how to use it?

**Comment by nullboundary** [comment]
Ok, readme is updated.

**Comment by runemadsen** [comment]
Peeeeeerfect!

**Pull request merged**
